include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    avoid_print: true

analyzer:
#  plugins:
#     - dart_code_metrics
 exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**.config.dart"
    - "*_test.dart"
    - "**/generated_plugin_registrant.dart"
 errors:
    invalid_annotation_target: ignore
